# Generated by Django 5.1.2 on 2025-11-20 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_courseapplication_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('specialization', models.CharField(choices=[('orthodontics', 'Ортодонтия'), ('therapy', 'Терапевтическая стоматология'), ('surgery', 'Хирургическая стоматология'), ('implantology', 'Имплантология'), ('periodontology', 'Пародонтология'), ('pediatric', 'Детская стоматология')], default='orthodontics', max_length=50)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
